version: '2'
services:
  mysimplelibrary-app:
    image: mysimplelibrary
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysimplelibrary-mysql:3306/mysimplelibrary?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://mysimplelibrary-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://mysimplelibrary-elasticsearch:9200
    ports:
      - 8090:8090
  mysimplelibrary-mysql:
    extends:
      file: mysql.yml
      service: mysimplelibrary-mysql
  mysimplelibrary-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: mysimplelibrary-elasticsearch
